services:
  testing-api:
    build: .
    container_name: testing-api
    restart: unless-stopped
    ports:
      - "13492:13492"
    env_file:
      - .env
    volumes:
      - ./.ssh/api-shutdown-key:/home/auditio-test/.ssh/api-shutdown-key:ro,Z
      - ./logs:/app/logs
    networks:
      - auditio-net

networks:
  auditio-net:
    driver: bridge