services:
  testing-api:
    build: .
    container_name: testing-api
    restart: unless-stopped
    ports:
      - "13492:13492"
    env_file:
      - .env
    volumes:
      - ./.ssh/api-shutdown-key:/home/auditio-test/.ssh/api-shutdown-key:ro,Z
      - logs:/app/logs
      - ./app/current_projects.json:/app/current_projects.json:rw,Z
    networks:
      - auditio-net

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      device: ./logs
      o: bind

networks:
  auditio-net:
    external: true